services:
  - type: web
    name: lamp-kit-collective
    runtime: docker
    repo: https://github.com/ally090699/lamp-kit-collective
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "mysql://$DB_USER:$DB_PASS@$DB_HOST:DB_PORT/$DB_NAME"
    disk:
      name: data
      mountPath: /var/www/html/public/assets/uploads
      sizeGB: 1
